# Generated by Django 6.0.3 on 2026-04-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mobile_money_provider',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash on Delivery'), ('mobile_money', 'Mobile Money'), ('paypal', 'PayPal'), ('stripe', 'Credit Card')], default='cash_on_delivery', max_length=20),
        ),
    ]
