# Generated by Django 6.0.3 on 2026-04-24 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_address_address_line1_alter_address_city_and_more'),
        ('orders', '0002_order_mobile_money_provider_order_mobile_number_and_more'),
        ('products', '0003_alter_productreview_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='orderstatushistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order Status History', 'verbose_name_plural': 'Order Status Histories'},
        ),
        migrations.AlterField(
            model_name='order',
            name='mobile_money_provider',
            field=models.CharField(blank=True, choices=[('mtn', 'MTN Mobile Money'), ('airtel', 'Airtel Money'), ('vodafone', 'Vodafone Cash'), ('orange', 'Orange Money'), ('tigo', 'Tigo Cash'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='mobile_number',
            field=models.CharField(blank=True, help_text="Customer's mobile number for payment", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.address'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
